#!/usr/bin/env bash
# shellcheck disable=SC1090

set -e
set -u

this_cmd="${BASH_SOURCE[0]}"
this_path="$(cd "$(dirname "$this_cmd")" && pwd)"

if [ "$#" -ne 3 ]; then
    echo "Usage: $this_cmd target.env path/apis.json path/openapi.json"
    exit 2
fi

echo "Source variables from the env file"
set -a; source "$this_path/$1"; set +a

echo -e "\nCreating a target resource group for deployment"
az group create \
    --name "$AZ_PREFIX-$AZ_ENVIRONMENT-$AZ_APP-rg" \
    --location "$AZ_LOCATION" \
    --subscription "$AZ_SUBSCRIPTION_ID" \
    --tags app="$AZ_APP" environment="$AZ_ENVIRONMENT" owner="$AZ_OWNER"

echo -e "\nCreating storage account for the API files"
az deployment group create \
    --resource-group "$AZ_PREFIX-$AZ_ENVIRONMENT-$AZ_APP-rg" \
    --subscription "$AZ_SUBSCRIPTION_ID" \
    --template-file "$this_path/sa.bicep" \
    -p sa_name="${AZ_PREFIX//-/}${AZ_ENVIRONMENT//-/}${AZ_APP//-/}sa" \
    -p tags="{'app': '$AZ_APP', 'environment': '$AZ_ENVIRONMENT', 'owner': '$AZ_OWNER'}"

echo -e "\nUploading APIs to storage account file share"
az storage file upload \
    --account-name "${AZ_PREFIX//-/}${AZ_ENVIRONMENT//-/}${AZ_APP//-/}sa" \
    --share-name share \
    --source "$2"

echo -e "\nCreating a deployment in the resource group"
az deployment group create \
    --resource-group "$AZ_PREFIX-$AZ_ENVIRONMENT-$AZ_APP-rg" \
    --subscription "$AZ_SUBSCRIPTION_ID" \
    --template-file "$this_path/main.bicep" \
    -p prefix="$AZ_PREFIX" \
    -p app="$AZ_APP" \
    -p environment="$AZ_ENVIRONMENT" \
    -p owner="$AZ_OWNER" \
    -p dns_zone_name="$AZ_DNS_ZONE_NAME" \
    -p dns_zone_rg_name="$AZ_DNS_ZONE_RG_NAME" \
    -p key_vault_name="$AZ_KEY_VAULT_NAME" \
    -p key_vault_rg_name="$AZ_KEY_VAULT_RG_NAME" \
    -p key_vault_cert_name="$AZ_KEY_VAULT_CERT_NAME"

echo -e "\nUploading API spec to storage account blob container"
az storage blob upload \
    --account-name "${AZ_PREFIX//-/}${AZ_ENVIRONMENT//-/}${AZ_APP//-/}sa" \
    --container-name apis \
    --name openapi.json \
    --file "$3"

echo -e "\nCreating API deployment in the resource group"
az deployment group create \
    --resource-group "$AZ_PREFIX-$AZ_ENVIRONMENT-$AZ_APP-rg" \
    --subscription "$AZ_SUBSCRIPTION_ID" \
    --template-file "$this_path/api.bicep" \
    -p apim_name="$AZ_PREFIX-$AZ_ENVIRONMENT-$AZ_APP-apim" \
    -p app_name="$AZ_APP" \
    -p api_backend_url="http://$AZ_APP-$AZ_ENVIRONMENT.$AZ_DNS_ZONE_NAME:8080" \
    -p api_spec="https://${AZ_PREFIX//-/}${AZ_ENVIRONMENT//-/}${AZ_APP//-/}sa.blob.core.windows.net/apis/openapi.json"

echo -e "\n✅ Successfully finished."
