# To install:

# brew bundle
# pre-commit install

repos:
# - repo: https://github.com/gruntwork-io/pre-commit
- repo: https://github.com/asyrjasalo/pre-commit
  rev: v0.1.12
  hooks:
  - id: terraform-fmt
  - id: terraform-validate
  - id: shellcheck

# - repo: https://github.com/antonbabenko/pre-commit-terraform
- repo: https://github.com/asyrjasalo/pre-commit-terraform
  rev: v1.45.0
  hooks:
  - id: terraform_tfsec
