# To install:

# pip install --upgrade pre-commit checkov
# pre-commit install

repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
  - id: terraform-fmt
  - id: terraform-validate
  - id: shellcheck

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
  - id: terraform_tfsec
  - id: checkov
