trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
- group: test

stages:
- stage: test
  displayName: Test environment
  jobs:
  - job: deploy
    displayName: Deploy to Azure
    steps:
      - script: |
          ls -al
          echo "$AZ_APP"
        failOnStderr: true
        displayName: Debug
        workingDirectory: bicep
