#!/usr/bin/env bash

# SC2086: Double quote to prevent globbing and word splitting
# shellcheck disable=SC2086

set -e

### constants ##################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### variables ##################################################################

: "${BUILD_ARGS:=""}"
: "${BUILD_DIR:="$this_path"}"
: "${BUILD_NAME:="$(date -u +%Y.%m.%d.post%H%M%S.dev"$(id -u)")"}"
: "${IMAGE_NAME:="${this_path##*/}"}"
: "${RUN_ARGS:="-p 8080:8080"}"

### build and run ##############################################################

docker build $BUILD_ARGS --tag "$IMAGE_NAME:$BUILD_NAME" "$BUILD_DIR"

docker run --rm \
  --user node \
  --cap-drop ALL \
  -it $RUN_ARGS \
  "$IMAGE_NAME:$BUILD_NAME" "$@"
