#!/usr/bin/env bash
# shellcheck disable=SC2034,SC2086

set -e

### constants ##################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root_path="$(cd "$this_path/.." && pwd)"

### variables ##################################################################

: "${BUILD_ARGS:="--pull --no-cache"}"
: "${BUILD_DIR:="$repo_root_path"}"

: "${IMAGE_KIND:="alpine"}"
: "${IMAGE_NAME:="mockoon"}"
: "${IMAGE_TAG:="$IMAGE_KIND"}"

: "${RUN_CMD:="--version"}"

### build ######################################################################

docker build \
  --file "$this_path/Dockerfile.$IMAGE_KIND" \
  $BUILD_ARGS \
  --tag "$IMAGE_NAME:$IMAGE_TAG" \
  "$BUILD_DIR"

### scan #######################################################################

docker scan \
   --accept-license \
   --exclude-base \
   --file "$this_path/Dockerfile.$IMAGE_KIND" \
   "$IMAGE_NAME:$IMAGE_TAG"

### run ########################################################################

BUILD_ARGS="--build-arg FROM_IMAGE=$IMAGE_NAME:$IMAGE_TAG" \
  "$repo_root_path/dockoon" $RUN_CMD
