ARG NODE_VERSION=14
FROM node:${NODE_VERSION}-alpine

# if no tzdata, will stick on UTC
ARG ADD_APK_PACKAGES="tzdata"
RUN apk --no-cache --update add ${ADD_APK_PACKAGES}

ARG TZ="Europe/Helsinki"
RUN cp /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone || true

USER node
WORKDIR /home/node

ARG ADD_NPM_PACKAGES="@mockoon/cli"
RUN npm install ${ADD_NPM_PACKAGES} --production --no-save

COPY --chown=node:node docker/runner.sh runner.sh
ENTRYPOINT ["sh", "runner.sh"]
